resources:
- name: platform-automation-tasks-s3
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((region))
    bucket: ((bucket))
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image-s3
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((region))
    bucket: ((bucket))
    regexp: platform-automation-image-(.*).tgz

- name: env
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((region))
    bucket: ((bucket))
    versioned_file: env.yml

- name: state
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((region))
    bucket: ((bucket))
    versioned_file: state.yml

- name: opsman-config
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((region))
    bucket: ((bucket))
    versioned_file: opsman.yml

jobs:
- name: delete-installation
  plan:
  - aggregate:
    - get: platform-automation-tasks-s3
      params:
        unpack: true
    - get: platform-automation-image-s3
      params:
        unpack: true
    - get: env
  - task: delete-installation
    image: platform-automation-image-s3
    file: platform-automation-tasks-s3/tasks/delete-installation.yml

- name: delete-vm
  plan:
  - aggregate:
    - get: platform-automation-tasks-s3
      params:
        unpack: true
    - get: platform-automation-image-s3
      params:
        unpack: true
    - get: env
      passed:
      - delete-installation
      trigger: true
    - get: state
    - get: opsman-config
  - task: delete-vm
    image: platform-automation-image-s3
    file: platform-automation-tasks-s3/tasks/delete-vm.yml
    input_mapping:
      config: opsman-config
    ensure:
      put: state
      params:
        file: generated-state/state.yml

